### ISSUE TITLE
Error while running plot_loop.py

### ISSUE THREAD

**Issue by raghavprasad13** [simonarvin/eyeloop#30] opened 2020-10-26 14:25 UTC
I'm encountering an error when I try to run `plot_loop.py` in the open_loop example. Initially, I got [this error](http://p.ip.fi/42Vm). I temporarily solved it by hardcoding `self.animal = "mouse"` in the Loop_parser constructor. However, after that, I faced [another error](http://p.ip.fi/uGbW). I'm not sure how to fix this.  
  
P.S. I used the `open-loop-log.json` file.  
  
P.P.S Is there any documentation regarding the keys in the JSON log file and what they represent?

**Comment by kinow** [comment] 2020-10-26 20:48
I've reproduced the issue. Looks like the plot example extends the `Parser` class, which requires an `animal` parameter. If the plot example class calls the `Parser` constructor, that should fix the error. But after that locally, I found a few more errors.

Trying to prepare a PR with what I've found, but as I don't know much about the JSON log file or the example code, it would need some review from @simonarvin or someone else :+1:

**Comment by simonarvin** [comment] 2020-10-27 09:26
Hi @raghavprasad13 

This error was caused by a legacy/modern format mismatch. This has been fixed in edad0fe2352a0bc2777554062aa7685a301083fb

Thanks for reporting it!

Best,
Simon

**Comment by raghavprasad13** [comment] 2020-10-27 13:49
Thank you @simonarvin and @kinow!  
I tried re-running the script after pulling the changes and I got [this error](http://p.ip.fi/idC4)  
After tinkering around for a bit I saw that `file.readlines()` in `Parser.load_log()` does not return the line in the JSON as is. For example, the first line in the log file is
>`{"time": 1590337137.7045662, "frame": 1, "blink": -1, "cr": [[-1, -1], -1, -1], "pupil": [[-1, -1], -1, -1]}`  

but printing `line` yields
> `{"time": 1590337137.7045662, "frame": 1, "blink": -1, "cr_dim": [-1, -1], "cr_cen": -1, "cr_ang": -1, "pupil_dim": [-1, -1], "pupil_cen": -1, "pupil_ang": -1}`  

What could be the reason for this and I suspect this is what is causing the aforementioned error in the first place because it doesn't get the key 'pupil'

**Comment by simonarvin** [comment] 2020-10-27 13:57
Hi @raghavprasad13 

I suspect you're loading the wrong log file (legacy format). Can you try again, making sure to load the new, re-formatted log?

Best,
Simon

**Comment by raghavprasad13** [comment] 2020-10-27 14:02
Yes @simonarvin I apologize 🙈
That was my mistake
Thank you very much for fixing this issue!

**Closed as completed** 2020-10-27 14:02 UTC
